### ISSUE TITLE
Compatibility with Eigen 3.2

### ISSUE THREAD

**Issue by stephane-caron** [jrl-umi3218/Eigen3ToPython#10]
Hi guys,

Cythonization of the bindings fails with Eigen 3.2 because (at least) ``AlignmentType`` is not defined:
```
Eigen3ToPython/include/eigen_wrapper.hpp:32:27: error: ‘AlignmentType’ was not declared in this scope
 using DynMap = Map<Mtype, AlignmentType::Aligned, DynStride>;
```
Best,

**Comment by haudren** [comment]
@stephane-caron : Sorry about this, AlignmentType is an Eigen `3.2.9` feature. Is it possible for you to upgrade?

**Comment by stephane-caron** [comment]
Sure, I can install Eigen from source. But then note that Eigen3ToPython is not compatible any more with the Eigen 3.2 distributed in Ubuntu 14.04 packages.

Also, maybe update Eigen 3.2 -> 3.2.9 in the deps list of the README.

**Comment by haudren** [comment]
Hum I guess we can add a small `#define` to keep compatibility, what do you think @gergondet ?

**Comment by gergondet** [comment]
I agree that this should work out of the box on Ubuntu 14.04 I think we can adopt the code to work with 3.2.x (x < 9) and without deprecation issue for 3.3.x (since Aligned should be Aligned16)

**Comment by haudren** [comment]
I'll need to check exactly the exact alignment but I think that the numpy data is actually 64-bytes aligned. I don't think it's that important ^^

**Comment by stephane-caron** [comment]
Okay, then I'll keep my "vanilla" Ubuntu install for now, and validate the install once you've made the change.

**Comment by stephane-caron** [comment]
Confirmed it works on 14.04. Thanks!
